name: Build

on: [push]

jobs:
  build:
    name: Validate, Analyze, and Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install HackMyResume and WkHtmlToPdf
      run: |
        sudo apt-get install wkhtmltopdf
        npm install -g hackmyresume
    - name: Npm Test and Build 
      id: build_resume
      run: |
        npm test
        npm run build --if-present
   
